### ISSUE TITLE
[Question] Defining global tags

### ISSUE THREAD

**Issue by abelsromero** [smallrye/smallrye-metrics#320]
Is it possible to define global tags that are added to all metrics?

For more detail I am migration an app to Quarkus and I can inject the `MetricRegistry` easilty but don't see any additional option. And checking `SmallRyeMetricsRecorder` does not provide any hint.

**Comment by jmartisk** [comment]
SmallRye Metrics accepts global tags if they are provided either as `MP_METRICS_TAGS` env variable, or `mp.metrics.tags` system property - if using Quarkus, you can add that property to you `application.properties`. Let me know if that helps. Thanks!

**Comment by abelsromero** [comment]
Worked perfecty with `mp.metrics.tags=hello=123,bye=456` in the properties or `MP_METRICS_TAGS="hello=123,bye=456"` in JVM, but in native when using the env variable (property works) in native I get the error below.

Do you preffer a different issue or should I report to Quarkus team first? I can prepare a reproduce project later.

```
09:14:07 ERROR [io.qu.ru.Application] (main) Error running Quarkus application: java.lang.IllegalStateException: No timer with metricID [MetricID{name='org.acme.getting.started.GreetingRepository.repo_save', tags=[bye="456",hello="123"]}] found in registry [io.smallrye.metrics.MetricsRegistryImpl@2d97810]
        at io.smallrye.metrics.interceptors.TimedInterceptor.timedCallable(TimedInterceptor.java:90)
        at io.smallrye.metrics.interceptors.TimedInterceptor.timedMethod(TimedInterceptor.java:70)
        at io.smallrye.metrics.interceptors.TimedInterceptor_Bean.intercept(TimedInterceptor_Bean.zig:259)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at org.acme.getting.started.GreetingRepository_Subclass.save(GreetingRepository_Subclass.zig:181)
        at org.acme.getting.started.GreetingRepository_ClientProxy.save(GreetingRepository_ClientProxy.zig:185)
        at org.acme.getting.started.CommandMain.run(CommandMain.java:26)
        at org.acme.getting.started.CommandMain_ClientProxy.run(CommandMain_ClientProxy.zig:42)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
```

**Comment by jmartisk** [comment]
Hmm. I've just tried it with native mode and there's the caveat that metrics are registered at build time, so they are registered using the `MP_METRICS_TAGS` value that you pass during build. If you pass a different value when starting your application, you will run into problems because metrics are already registered with different global tags.

This basically means that you have to pass the same value during build as you do for runtime. 

Perhaps Quarkus could ignore the value set for runtime and always consider only the one that was given during build...? I'm not super familiar with the internals of the config mechanisms, but I suppose this should (somehow) be possible. You may file a Quarkus issue for this ;)

**Comment by abelsromero** [comment]
If I understand correctly you propose to fix it so it alwasy gets the value during build time?
If so, this does not make sense to me. The idea is being able to separate configuration from code and have easy configuration method for conteinarized environments.
For example in our case we spin the same component for different consumers, each one with different parameters set through environment variables.

If it's OK for you, I'll move this to the Quarkus mailing list.

**Comment by jmartisk** [comment]
Many configuration values that Quarkus accepts are not possible to be overridden at application startup, they are build-only. If you look at https://quarkus.io/guides/all-config it's the ones with a lock icon on the left. This is by design, because they have already been acted upon during the build phase, and can't be changed later. The `MP_METRICS_TAGS` property should be treated as one of them.
The bug I see here is that while it should be treated as a build-time property, it is possible to override it at runtime, which inevitably leads to problems.

**Comment by abelsromero** [comment]
Haven't realised some properties where build-time until now, many thanks for the explanation.
Passing it during build works, provided no additiona value is set at runtime.

> Perhaps Quarkus could ignore the value set for runtime and always consider only the one that was given during build...? I'm not super familiar with the internals of the config mechanisms, but I suppose this should (somehow) be possible. You may file a Quarkus issue for this ;)

Will do :+1:  Thanks again!
