### ISSUE TITLE
injection of MetricRegistry won't work with weld 3.1.7

### ISSUE THREAD

**Issue by Hint10** [smallrye/smallrye-metrics#415]
```
package com.myproject.metrics;

import java.lang.management.ManagementFactory;
import java.lang.management.ThreadMXBean;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.Initialized;
import javax.enterprise.event.Observes;
import javax.inject.Inject;

import org.eclipse.microprofile.metrics.Metadata;
import org.eclipse.microprofile.metrics.MetricRegistry;

@ApplicationScoped
public class Jvm {

	private final ThreadMXBean threadBean = ManagementFactory.getThreadMXBean();

	@Inject
	private MetricRegistry registry;

	void init(@Observes @Initialized(ApplicationScoped.class) final Object init) {
		registry.gauge(
				Metadata.builder().withName("threads_current").withDescription("Current thread count of a JVM").build(),
				() -> threadBean.getThreadCount());

		}

}



```
will lead to 

`org.jboss.weld.exceptions.WeldException: WELD-001524: Unable to load proxy class for bean Producer Method [MetricRegistry] with qualifiers [@RegistryType @Default @Any] declared as [[UnbackedAnnotatedMethod] @Produces @Default @RegistryType @ApplicationScoped public io.smallrye.metrics.MetricRegistries.getApplicationRegistry()] with class class java.lang.Object
    at org.jboss.weld.bean.proxy.ProxyFactory.getProxyClass(ProxyFactory.java:381)
    at org.jboss.weld.bean.proxy.ProxyFactory.run(ProxyFactory.java:334)
    at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:326)
    at org.jboss.weld.bean.proxy.ClientProxyFactory.create(ClientProxyFactory.java:83)
    at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:205)
    at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:195)
    at org.jboss.weld.bean.proxy.ClientProxyProvider.access$100(ClientProxyProvider.java:44)
    at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.apply(ClientProxyProvider.java:52)
    at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.apply(ClientProxyProvider.java:48)
    at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$new$0(ReentrantMapBackedComputingCache.java:55)
    at org.jboss.weld.util.LazyValueHolder$1.computeValue(LazyValueHolder.java:32)
    at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
    at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:72)
    at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:78)
    at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:229)
    at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:688)
    at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:794)
    at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
    at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:345)
    at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:356)
    at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:69)
    at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
    at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:71)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:117)
    at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:161)
    at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
    at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
    at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
    at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:67)
    at org.jboss.weld.event.ObserverMethodImpl.getReceiver(ObserverMethodImpl.java:360)
    at org.jboss.weld.event.ObserverMethodImpl.getReceiverIfExists(ObserverMethodImpl.java:347)
    at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:305)
    at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
    at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
    at org.jboss.weld.util.Observers.notify(Observers.java:166)
    at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
    at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
    at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
    at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159)
    at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632)
    at org.jboss.weld.environment.se.WeldContainer.fireContainerInitializedEvent(WeldContainer.java:236)
    at org.jboss.weld.environment.se.WeldContainer.endInitialization(WeldContainer.java:188)
    at org.jboss.weld.environment.se.Weld.initialize(Weld.java:817)`

**Comment by Hint10** [comment]
https://issues.redhat.com/browse/WELD-2662
