### ISSUE TITLE
Can not run Metrics TCK

### ISSUE THREAD

**Issue by jmesnil** [smallrye/smallrye-metrics#8]
On my pristine new laptop, I'm not able to run the TCK.
It is passing on semaphore so my issue is likely environmental but I have some doubt.

When I run the tck, it fails with:

```
$ mvn clean package
...
[INFO] ---------------< io.smallrye:smallrye-metrics-rest-tck >----------------
[INFO] Building SmallRye: MicroProfile Metrics TCK 1.1.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ smallrye-metrics-rest-tck ---
[INFO] Deleting /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ smallrye-metrics-rest-tck ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ smallrye-metrics-rest-tck ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ smallrye-metrics-rest-tck ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ smallrye-metrics-rest-tck ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/test-classes
[INFO]
[INFO] --- maven-dependency-plugin:2.8:unpack (unpack) @ smallrye-metrics-rest-tck ---
[INFO] Configured Artifact: org.wildfly:wildfly-servlet-dist:13.0.0.Final:zip
[INFO] Unpacking /Users/jmesnil/.m2/repository/org/wildfly/wildfly-servlet-dist/13.0.0.Final/wildfly-servlet-dist-13.0.0.Final.zip to /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target with includes "" and excludes ""
[INFO]
[INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ smallrye-metrics-rest-tck ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.eclipse.microprofile.metrics.test.MpMetricTest
Sep 27, 2018 2:42:17 PM org.jboss.as.arquillian.container.managed.ManagedDeployableContainer startInternal
WARNING: Bundles path is deprecated and no longer used.
Sep 27, 2018 2:42:17 PM org.jboss.as.arquillian.container.managed.ManagedDeployableContainer startInternal
INFO: Starting container with: [/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java, -D[Standalone], -Xms64m, -Xmx512m, -Djava.net.preferIPv4Stack=true, -Djava.awt.headless=true, -Djboss.modules.system.pkgs=org.jboss.byteman, -ea, -Djboss.home.dir=/Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final, -Dorg.jboss.boot.log.file=/Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone/log/server.log, -Dlogging.configuration=file:/Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone/configuration/logging.properties, -jar, /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/jboss-modules.jar, -mp, /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/modules, org.jboss.as.standalone, -Djboss.home.dir=/Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final, -Djboss.server.base.dir=/Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone, -Djboss.server.log.dir=/Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone/log, -Djboss.server.config.dir=/Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone/configuration]
Sep 27, 2018 2:42:17 PM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 5.0.0.Final
Sep 27, 2018 2:42:17 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.5.1.Final
Sep 27, 2018 2:42:17 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.5.1.Final
Sep 27, 2018 2:42:17 PM org.wildfly.security.Version <clinit>
INFO: ELY00001: WildFly Elytron version 1.1.0.Final
14:42:18,027 INFO  [org.jboss.modules] (main) JBoss Modules version 1.8.5.Final
14:42:22,146 INFO  [org.jboss.msc] (main) JBoss MSC version 1.4.2.Final
14:42:22,154 INFO  [org.jboss.threads] (main) JBoss Threads version 2.3.2.Final
14:42:22,260 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: WildFly Servlet 13.0.0.Final (WildFly Core 5.0.0.Final) starting
14:42:22,835 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
14:42:22,854 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 11) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
14:42:22,854 INFO  [org.wildfly.security] (ServerService Thread Pool -- 9) ELY00001: WildFly Elytron version 1.3.3.Final
14:42:22,881 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
14:42:22,894 INFO  [org.xnio] (MSC service thread 1-7) XNIO version 3.6.3.Final
14:42:22,901 INFO  [org.xnio.nio] (MSC service thread 1-7) XNIO NIO Implementation Version 3.6.3.Final
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xnio.nio.NioXnio$2 (jar:file:/Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/modules/system/layers/base/org/jboss/xnio/nio/main/xnio-nio-3.6.3.Final.jar!/) to constructor sun.nio.ch.KQueueSelectorProvider()
WARNING: Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
14:42:22,926 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 21) WFLYNAM0001: Activating Naming Subsystem
14:42:22,927 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 19) WFLYIO001: Worker 'default' has auto-configured to 24 core threads with 192 task threads based on your 12 available processors
14:42:22,931 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 23) WFLYSEC0002: Activating Security Subsystem
14:42:22,931 INFO  [org.jboss.as.ee] (ServerService Thread Pool -- 17) WFLYEE0119: The system property 'ee8.preview.mode' is NOT set to 'true'. For provided EE 8 APIs where the EE 8 version of the API differs from what is supported in EE 7, the EE 7 variant of the API will be used. Support for this setting will be removed once all EE 8 APIs are provided and certified.
14:42:22,933 INFO  [org.jboss.as.security] (MSC service thread 1-2) WFLYSEC0001: Current PicketBox version=5.0.2.Final
14:42:22,950 INFO  [org.jboss.as.naming] (MSC service thread 1-1) WFLYNAM0003: Starting Naming Service
14:42:22,961 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0003: Undertow 2.0.9.Final starting
14:42:22,964 INFO  [org.jboss.remoting] (MSC service thread 1-2) JBoss Remoting version 5.0.7.Final
14:42:22,988 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 25) WFLYUT0014: Creating file handler for path '/Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/welcome-content' with options [directory-listing: 'false', follow-symlink: 'false', case-sensitive: 'true', safe-symlink-paths: '[]']
14:42:22,993 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0012: Started server default-server.
14:42:22,995 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0018: Host default-host starting
14:42:23,041 INFO  [org.jboss.as.patching] (MSC service thread 1-3) WFLYPAT0050: WildFly Servlet cumulative patch ID is: base, one-off patches include: none
14:42:23,050 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0006: Undertow HTTP listener default listening on 127.0.0.1:8080
14:42:23,054 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-8) WFLYDM0111: Keystore /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
14:42:23,058 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-3) WFLYDS0013: Started FileSystemDeploymentService for directory /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone/deployments
14:42:23,071 WARN  [org.jboss.as.domain.http.api.undertow] (MSC service thread 1-1) WFLYDMHTTP0003: Unable to load console module for slot main, disabling console
14:42:23,108 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0006: Undertow HTTPS listener https listening on 127.0.0.1:8443
14:42:23,150 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
14:42:23,152 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
14:42:23,152 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
14:42:23,152 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Servlet 13.0.0.Final (WildFly Core 5.0.0.Final) started in 5482ms - Started 137 of 141 services (36 services are lazy, passive or on-demand)
e9e944f7-e20c-406a-935a-bc42ab121c72.jar:
/org/
/org/eclipse/
/org/eclipse/microprofile/
/org/eclipse/microprofile/metrics/
/org/eclipse/microprofile/metrics/test/
/org/eclipse/microprofile/metrics/test/MetricAppBean.class
/META-INF/
/META-INF/beans.xml
14:42:24,600 INFO  [org.jboss.as.repository] (management-handler-thread - 1) WFLYDR0001: Content added at location /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone/data/content/fe/dccd5738c8f5fc143e15305d3bf6f592918087/content
14:42:24,616 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0027: Starting deployment of "test.war" (runtime-name: "test.war")
14:42:25,375 INFO  [org.jboss.weld.environment.servletWeldServlet] (ServerService Thread Pool -- 11) WELD-ENV-001008: Initialize Weld using ServletContainerInitializer
14:42:25,384 INFO  [org.jboss.weld.Version] (ServerService Thread Pool -- 11) WELD-000900: 2.4.7 (Final)
14:42:25,461 INFO  [org.jboss.weld.environment.deployment.discovery.DefaultBeanArchiveScanner] (ServerService Thread Pool -- 11) Unable to adapt URL: vfs:/content/test.war/WEB-INF/lib/e9e944f7-e20c-406a-935a-bc42ab121c72.jar/META-INF/beans.xml, using its external form instead
14:42:25,518 INFO  [org.jboss.weld.Bootstrap] (ServerService Thread Pool -- 11) WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
14:42:25,631 INFO  [io.smallrye.metrics] (ServerService Thread Pool -- 11) MicroProfile: Metrics activated
14:42:25,709 INFO  [org.jboss.weld.environment.servletUndertow] (ServerService Thread Pool -- 11) WELD-ENV-001302: Undertow detected, CDI injection will be available in Servlets, Filters and Listeners.
14:42:25,896 INFO  [io.smallrye.metrics] (ServerService Thread Pool -- 11) Converted [2] config entries and added [4] replacements
14:42:25,898 INFO  [io.smallrye.metrics] (ServerService Thread Pool -- 11) Converted [3] config entries and added [18] replacements
14:42:25,922 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 11) WFLYUT0021: Registered web context: '/' for server 'default-server'
14:42:26,366 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0010: Deployed "test.war" (runtime-name : "test.war")
14:42:26,670 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 11) WFLYUT0022: Unregistered web context: '/' from server 'default-server'
14:42:26,700 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0028: Stopped deployment test.war (runtime-name: test.war) in 33ms
14:42:26,759 INFO  [org.jboss.as.repository] (management-handler-thread - 1) WFLYDR0002: Content removed from location /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone/data/content/fe/dccd5738c8f5fc143e15305d3bf6f592918087/content
14:42:26,759 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0009: Undeployed "test.war" (runtime-name: "test.war")
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.719 s <<< FAILURE! - in org.eclipse.microprofile.metrics.test.MpMetricTest
[ERROR] org.eclipse.microprofile.metrics.test.MpMetricTest  Time elapsed: 9.718 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.eclipse.microprofile.metrics.test.MpMetricTest.setup(MpMetricTest.java:101)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at org.eclipse.microprofile.metrics.test.MpMetricTest.setup(MpMetricTest.java:101)

[INFO] Running org.eclipse.microprofile.metrics.test.ReusableMetricsTest
14:42:27,319 INFO  [org.jboss.as.repository] (management-handler-thread - 1) WFLYDR0001: Content added at location /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone/data/content/c8/757a98bdbe8979b0c41f20a8ade55be56432e6/content
14:42:27,326 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of "test.war" (runtime-name: "test.war")
14:42:27,784 INFO  [org.jboss.weld.environment.servletWeldServlet] (ServerService Thread Pool -- 9) WELD-ENV-001008: Initialize Weld using ServletContainerInitializer
14:42:27,793 INFO  [org.jboss.weld.Version] (ServerService Thread Pool -- 9) WELD-000900: 2.4.7 (Final)
14:42:27,817 INFO  [org.jboss.weld.environment.deployment.discovery.DefaultBeanArchiveScanner] (ServerService Thread Pool -- 9) Unable to adapt URL: vfs:/content/test.war/WEB-INF/lib/d23cf348-a136-44c0-9a0e-8142a55ceb56.jar/META-INF/beans.xml, using its external form instead
14:42:27,857 INFO  [org.jboss.weld.Bootstrap] (ServerService Thread Pool -- 9) WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
14:42:27,963 INFO  [io.smallrye.metrics] (ServerService Thread Pool -- 9) MicroProfile: Metrics activated
14:42:28,019 INFO  [org.jboss.weld.environment.servletUndertow] (ServerService Thread Pool -- 9) WELD-ENV-001302: Undertow detected, CDI injection will be available in Servlets, Filters and Listeners.
14:42:28,187 INFO  [io.smallrye.metrics] (ServerService Thread Pool -- 9) Converted [2] config entries and added [4] replacements
14:42:28,189 INFO  [io.smallrye.metrics] (ServerService Thread Pool -- 9) Converted [3] config entries and added [18] replacements
14:42:28,190 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 9) WFLYUT0021: Registered web context: '/' for server 'default-server'
14:42:28,230 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0010: Deployed "test.war" (runtime-name : "test.war")
14:42:28,242 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 9) WFLYUT0022: Unregistered web context: '/' from server 'default-server'
14:42:28,269 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0028: Stopped deployment test.war (runtime-name: test.war) in 28ms
14:42:28,280 INFO  [org.jboss.as.repository] (management-handler-thread - 1) WFLYDR0002: Content removed from location /Users/jmesnil/Developer/smallrye-metrics/testsuite/rest-tck/target/wildfly-servlet-13.0.0.Final/standalone/data/content/c8/757a98bdbe8979b0c41f20a8ade55be56432e6/content
14:42:28,280 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0009: Undeployed "test.war" (runtime-name: "test.war")
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.486 s <<< FAILURE! - in org.eclipse.microprofile.metrics.test.ReusableMetricsTest
[ERROR] org.eclipse.microprofile.metrics.test.ReusableMetricsTest  Time elapsed: 1.485 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.jayway.restassured.RestAssured
        at org.eclipse.microprofile.metrics.test.ReusableMetricsTest.setup(ReusableMetricsTest.java:75)

14:42:28,289 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0236: Suspending server with no timeout.
14:42:28,290 INFO  [org.jboss.as.server] (Management Triggered Shutdown) WFLYSRV0241: Shutting down in response to management operation 'shutdown'
14:42:28,298 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0008: Undertow HTTP listener default suspending
14:42:28,299 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0008: Undertow HTTPS listener https suspending
14:42:28,301 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-6) WFLYUT0019: Host default-host stopping
14:42:28,304 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0007: Undertow HTTP listener default stopped, was bound to 127.0.0.1:8080
14:42:28,304 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0007: Undertow HTTPS listener https stopped, was bound to 127.0.0.1:8443
14:42:28,306 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0004: Undertow 2.0.9.Final stopping
14:42:28,316 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0050: WildFly Servlet 13.0.0.Final (WildFly Core 5.0.0.Final) stopped in 20ms
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   MpMetricTest.setup:101 » NoClassDefFound javax/xml/bind/JAXBException
[ERROR]   ReusableMetricsTest.setup:75 NoClassDefFound Could not initialize class com.ja...
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.190 s
[INFO] Finished at: 2018-09-27T14:42:28+02:00
[INFO] ------------------------------------------------------------------------
```

The `NoClassDefFound` error on `com.jayway.restassured.RestAssured` seems genuine to me.
The dependency to `com.jayway.restassured:rest-assured` in the Metrics TCK is using the `compile` scope:

```
$ mvn dependency:tree
...
[INFO] +- org.eclipse.microprofile.metrics:microprofile-metrics-rest-tck:jar:1.1:compile
[INFO] |  +- com.jayway.restassured:rest-assured:jar:2.4.0:compile
```

That seems normal that the class is not found at runtime during the test.

**Comment by kenfinnigan** [comment]
What JDK are you using?

**Comment by jmesnil** [comment]
```
$ java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

**Comment by kenfinnigan** [comment]
I'm almost 100% sure that's the issue.

MP is currently only guaranteed to run on JDK 8, same as Thorntail

**Comment by jmesnil** [comment]
You are right, the TCK passes with JDK8
